apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql
data:
  my.cnf: |
    [client]
    default-character-set=utf8mb3

    [mysql]
    default-character-set=utf8mb3

    [mysqld]
    init-connect='SET NAMES utf8mb3'
    character-set-server=utf8mb3

    max_allowed_packet=100M

    #
    # Fine Tuning
    #
    [mysqld]
    key_buffer_size         = 16M
    read_buffer_size        = 60K
    sort_buffer_size        = 1M
    innodb_buffer_pool_size = 64M
    tmp_table_size          = 8M
    max_allowed_packet      = 16M
    thread_stack            = 192K
    thread_cache_size       = 8

    # This replaces the startup script and checks MyISAM tables if needed
    # the first time they are touched
    myisam-recover-options  = BACKUP
    max_connections         = 25
