apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-mysql
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
