---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hairpin-proxy-controller-cr
rules:
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hairpin-proxy-controller-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hairpin-proxy-controller-cr
subjects:
  - kind: ServiceAccount
    name: hairpin-proxy-controller-sa
    namespace: hairpin-proxy

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hairpin-proxy-controller-r
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - coredns
    verbs:
      - get
      - watch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hairpin-proxy-controller-rb
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hairpin-proxy-controller-r
subjects:
  - kind: ServiceAccount
    name: hairpin-proxy-controller-sa
    namespace: hairpin-proxy
