{{- $fullName := include "alterconso.fullname" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-webapp
  labels:
    {{- include "alterconso.labels" . | nindent 4 }}
spec:
  {{- if not .Values.alterconso.autoscaling.enabled }}
  replicas: {{ .Values.alterconso.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "alterconso.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.alterconso.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "alterconso.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.alterconso.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alterconso.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.alterconso.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.alterconso.initContainers | nindent 8 }}
      containers:
        {{- range $name, $container := .Values.alterconso.containers }}
        - name: {{ $name }}
          image: "{{ $container.image.repository }}:{{ $container.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $container.image.pullPolicy }}
          ports:
            {{- toYaml $container.ports | nindent 10 }}
          volumeMounts:
            - name: {{ $.Release.Name }}-webapp-volume
              mountPath: "/var/www/alterconso/config.xml"
              subPath: config.xml
              readOnly: true
            - name: {{ $.Release.Name }}-webapp-volume
              mountPath: "/etc/apache2/sites-available/{{ $.Values.alterconso.configuration.webapp.vhost }}.conf"
              subPath: "vhost.conf"
              readOnly: true
            - name: {{ $.Release.Name }}-webapp-volume
              mountPath: "/etc/apache2/sites-enabled/{{ $.Values.alterconso.configuration.webapp.vhost }}.conf"
              subPath: "vhost.conf"
              readOnly: true
          securityContext:
            {{- toYaml $container.securityContext | nindent 12 }}
          resources:
            {{- toYaml $container.resources | nindent 12 }}
          env:
            {{- range $key, $value := $container.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- range $key, $value := $container.env_as_secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-webapp
                  key: {{ $key }}
            {{- end }}
         {{- end }}
      volumes:
      - name: {{ .Release.Name }}-webapp-volume
        configMap:
          name: {{ .Release.Name }}-webapp
          items:
          - key: config.xml
            path: config.xml
          - key: vhost.conf
            path: vhost.conf
      {{- with .Values.alterconso.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alterconso.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alterconso.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

{{- if .Values.alterconso.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}-webapp
spec:
  {{- with .Values.alterconso.autoscaling }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}-webapp
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}

---

{{- if .Values.alterconso.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alterconso.serviceAccountName" . }}
  labels:
    {{- include "alterconso.labels" . | nindent 4 }}
  {{- with .Values.alterconso.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-webapp
  labels:
    {{- include "alterconso.labels" . | nindent 4 }}
spec:
  type: {{ .Values.alterconso.service.type }}
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv6
    - IPv4
  ports:
    {{- range $port := .Values.alterconso.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.target }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "alterconso.selectorLabels" . | nindent 4 }}